# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Colaboradados
author: "Judite Cypreste"
keywords: "dados, bases de dados, jornalismo de dados, data science, analise de dados, judite cypreste"
email: colaboradados@gmail.com
description: "A base colaborativa de dados que tem como objetivo difundir informação. Pensando em auxiliar jornalistas de dados, cientistas de dados e a toda a sociedade, fizemos um banco de bases de dados, onde a ideia é simples: reunir links de bases de dados sérias e organizadas sobre vários assuntos em um só lugar."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://colaboradados.github.io" # the base hostname & protocol for your site

# Logo settings
logo-image-url: images/colaboradados.png

# Social settings
github_username: colaboradados
twitter_username: colaboradados
instagram_username: colaboradados

# Build settings
markdown: kramdown

# Layout settings
home-link-in-menu: yes

collections:
  podcasts:
    output: true
